# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 756e941a35679d869584ef36c0661b6c4da32318cc7266d6c1d4a55443015f1c5103872aa4e0fed67be04ed4eca07ee657322e0fd7615ade36969f02469b644e

test:
  secret_key_base: 45a54aa8e1746411c7b72b10532af9ca52809ea4602729733a14f88fa329900ccfe6b8ff30e6e709a624277a6f98728b3161c9cb47ca07ce2025316b04bf3bd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
